#!/bin/sh

CVSDIR=/home/dave/cvs/MegaTunix
ISS_FILE=dave/cvs/MegaTunix/MegaTunix.iss
DRIVE=L

SUFFIX=`grep SUFFIX ${CVSDIR}/MegaTunix.iss |cut -f2 -d= |tr -d [:cntrl:]`
wine ~/.wine/drive_c/Program\ Files/Inno\ Setup\ 5/ISCC.exe ${DRIVE}:/${ISS_FILE}
mv ${CVSDIR}/Output/setup.exe ${CVSDIR}/Output/megatunix-${SUFFIX}-setup.exe
