#!/bin/sh

GITDIR=/home/dave/git/MegaTunix
ISS_FILE=dave/git/MegaTunix/MegaTunix32_dbg.iss
DRIVE=L

VERSION=$(grep PACKAGE_VERSION ${GITDIR}/config.h |cut -f2 -d\")
SUFFIX=`cat ${GITDIR}/include/version.h |grep SUFFIX | cut -f2 -d\" |tr -d [:cntrl:]`
wine ~/.wine/drive_c/Program\ Files/Inno\ Setup\ 5/ISCC.exe "${DRIVE}":/"${ISS_FILE}"
mv "${GITDIR}"/Output/setup.exe "${GITDIR}"/../MTX_Builds/Output/windows/megatunix-"${VERSION}"-"${SUFFIX}"-win32_dbg-setup.exe && cd "${GITDIR}"/../MTX_Builds/Output/windows/ && zip -Z store megatunix-"${VERSION}"-"${SUFFIX}"-win32_dbg-setup.zip megatunix-"${VERSION}"-"${SUFFIX}"-win32_dbg-setup.exe && cd -

echo ""
echo "File name is ${GITDIR}/../MTX_Builds/Output/windows/megatunix-${SUFFIX}-win32_dbg-setup.zip"
