#!/bin/sh

if [ ! -d .git ] ; then
	echo "This needs to be run from the top level of the working copy"
	exit -1
fi

ISS_FILE=MegaTunix32.iss
HASH=`git log -n1 |grep ^commit |cut -f2 -d\  |head -c8`
VERSION=$(grep PACKAGE_VERSION config.h |cut -f2 -d\")
iscc ${ISS_FILE}
mv Output/setup.exe Output/megatunix-"${VERSION}"-"${HASH}"-win32-setup.exe 
echo ""
echo "File name is Output/megatunix-${VERSION}-${HASH}-win32-setup.zip"
