#!/bin/sh

GITDIR=/home/dave/git/MegaTunix
ISS_FILE=dave/git/MegaTunix/MegaTunix.iss
DRIVE=L

SUFFIX=`cat ${GITDIR}/include/version.h |grep SUFFIX | cut -f2 -d\" |tr -d [:cntrl:]`
wine ~/.wine/drive_c/Program\ Files/Inno\ Setup\ 5/ISCC.exe "${DRIVE}":/"${ISS_FILE}"
mv "${GITDIR}"/Output/setup.exe "${GITDIR}"/../MTX_Builds/Output/windows/megatunix-"${SUFFIX}"-setup.exe
echo ""
echo "File name is ${GITDIR}/../MTX_Builds/Output/windows/megatunix-${SUFFIX}-setup.exe"
