#!/bin/sh
# Manual cross linker script because it won't cross link because of libtool
# barfing on things.. (lack of .la files I think... )
echo "Linking megatunix.exe for win32 (cross compilation..)"

i386-mingw32msvc-gcc -mms-bitfields -I/target/include/hacks  -Wall  -O2  -L/opt/cross-tools/i386-mingw32msvc/lib -o megatunix.exe  3d_vetable.o about_gui.o bitfield_handlers.o comms.o comms_gui.o configfile.o conversions.o core_gui.o dataio.o datalogging_gui.o debugging.o dep_loader.o dep_processor.o dispatcher.o fileio.o general_gui.o getfiles.o gui_handlers.o init.o interrogate.o keyparser.o listmgmt.o logviewer_core.o logviewer_gui.o lookuptables.o main.o memory_gui.o mode_select.o notifications.o offline.o post_process.o req_fuel.o rtv_map_loader.o rtv_processor.o runtime_gui.o runtime_sliders.o serialio.o stringmatch.o tabloader.o tag_loader.o threads.o timeout_handlers.o tuning_gui.o user_outputs.o vetable_gui.o vex_support.o warmwizard_gui.o widgetmgmt.o -L/target/lib  \
		-luser32 \
		-lgdi32 \
		-lkernel32 \
		-lws2_32 \
		-lgw32c \
		-lole32 \
		-lglu32  \
		-lopengl32 \
		-lz  \
		-luuid \
		-lfreetype \
		-lpango-1.0  \
		-lpangowin32-1.0 \
		-liconv   \
		-lglib-2.0  \
		-latk-1.0  \
		-lgobject-2.0  \
		-lgmodule-2.0  \
		-lgtk-win32-2.0  \
		-lgdk-win32-2.0  \
		-lgdk_pixbuf-2.0  \
		-lglade-2.0  \
		-lxml2  \
		-lgthread-2.0 \
		-lgtkglext-win32-1.0 \
		-lgdkglext-win32-1.0 \
		-L../mtxmatheval -lmtxmatheval  \
		-lfl -ltermios 
