#!/bin/bash

DEB_RELEASES="lenny hardy lucid maverick oneiric precise"

trap "{ echo \"ABORT!!\"; exit 255; }" SIGINT SIGTERM

if [ $# -gt 0 ]; then
	dists="$*"
	echo "Dist(s) specified on CLI is \"$dists\""
else
	dists="$DEB_RELEASES"
fi

echo "Building for dists \"$dists\""
for dist in `echo "$dists"` ; do
	echo "Building for Distro $dist"
	pdebuild --buildresult ../MTX_Builds/Output/"$dist" --pbuilderroot "sudo DIST=$dist"
	if [ $? -ne 0 ] ; then
		echo "Build failure for dist $dist"
		exit -1
	fi
done
