#!/bin/bash

DEB_RELEASES="hardy intrepid jaunty karmic"

trap "{ echo \"ABORT!!\"; exit 255; }" SIGINT SIGTERM
if [ $# -eq 1 ]; then
	dist=$1
	echo "Dist specified on CLI is \"$dist\""
pdebuild --buildresult Output/"$dist" --pbuilderroot "sudo DIST=$dist"
else
	echo "Building for dists \"$DEB_RELEASES\""
	for dist in `echo "$DEB_RELEASES"` ; do
		pdebuild --buildresult ../MTX_Builds/Output/"$dist" --pbuilderroot "sudo DIST=$dist"
	done
fi
