#!/bin/bash


G_SLICE=always-malloc G_DEBUG=gc-friendly,resident-modules valgrind --show-reachable=yes --tool=memcheck --num-callers=45 -v --leak-check=full --suppressions=${HOME}/git/MegaTunix/contrib/mtx.supp --log-file=/tmp/log ./$*
