#!/bin/bash

git pull && ./autogen.sh --enable-debug && make clean && make -j2 && \
sudo make install && \
sudo ldconfig

echo "To get valid debug info, cd src/.libs ; gdb ./megatunix"
echo "Type \"run --g-fatal-warnings\""
echo "When it craps itself, type \"backtrace\" and send the output to me"
