#!/bin/sh

. cross32
CPUS=`cat /proc/cpuinfo |grep -c ^processor`

make distclean
cross32-configure ./configure --prefix=/opt/crossroot32/dest $* && \
	make -j${CPUS}  && rm -rf /opt/crossroot32/dest/* && make install && \
	./contrib/builder32 && \
. uncross 
# make distclean
