#!/bin/sh

. cross64

make distclean
cross64-configure ./configure --prefix=/opt/crossroot64/dest $* && \
	make -j5  && rm -rf /opt/crossroot64/dest/* && make install && \
	./contrib/builder64 && \
. uncross 
# make distclean
