#!/bin/sh

if [ -h /target ]; then 
	sudo rm /target && sudo ln -sf /opt/crossroot64 /target 
else
	sudo ln -sf /opt/crossroot64 /target
fi
. cross64

make distclean
cross64-configure ./configure --prefix=/target/dest $* && \
	make -j3  && rm -rf /target/dest/* && make install && \
	./contrib/builder64 && \
. uncross 
# make distclean
