#!/bin/sh

. cross

make distclean
cross-configure --disable-shared --prefix=/target/dest $* && \
	make -j3  && rm -rf /target/dest/* && make install && \
	./contrib/builder && \
. uncross 
# make distclean
