Document: megatunix
Title: Debian megatunix Manual
Author: <insert document author here>
Abstract: This manual describes what megatunix is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/megatunix/megatunix.sgml.gz

Format: postscript
Files: /usr/share/doc/megatunix/megatunix.ps.gz

Format: text
Files: /usr/share/doc/megatunix/megatunix.text.gz

Format: HTML
Index: /usr/share/doc/megatunix/html/index.html
Files: /usr/share/doc/megatunix/html/*.html

  
